#!/usr/bin/with-contenv sh
# Find status of -e VPN and -e PORT_F when passed at runtime
# and set options for variables to corresponing commands,
# or announce error with -e PORT_F and continue, or
# announce fatal error with -e VPN and exit. <-- To avoid exposing IP if set incorrectly
case "$VPN" in
     "") echo "[services.d] [INFO] -e VPN is not set, VPN not bound to app"
         break ;;
    yes) echo "[services.d] [INFO] VPN is bound to app"
         sleep 5; /config/scripts/init_bind.sh ;;
      *) echo "[services.d] [CRIT] -e VPN is set incorrectly; set -e VPN=yes or leave unset....exiting...."
         exit 1 ;;
esac
case "$NEW_UI" in
      "") export TRANSMISSION_WEB_HOME=/usr/share/transmission/web ;;
     yes) echo "[services.d] [INFO] -e NEW_UI set; using Combustion UI"
          export TRANSMISSION_WEB_HOME=/app/combustion ;;
       *) echo "[services.d] [WARN] -e NEW_UI set incorrectly; using Default UI"
          export TRANSMISSION_WEB_HOME=/usr/share/transmission/web ;;
esac
exec \
	s6-setuidgid abc /usr/bin/transmission-daemon \
	-g /config -c /watch -f

