#!/usr/bin/with-contenv sh
# Find status of -e VPN and -e PORT_F when passed at runtime
# and set options for variables to corresponing commands,
# or announce error with -e PORT_F and continue, or
# announce fatal error with -e VPN and exit. <-- To avoid exposing IP if set incorrectly
case "$VPN" in
     "") echo "[services.d] [INFO] -e VPN is not set, VPN not bound to app"
         break ;;
    yes) case "$PORT_F" in
        "") sleep 5; /config/scripts/init_bind.sh 
            echo "[services.d] [INFO] VPN is bound to app; not checking for forwarded ports" ;;
       yes) sleep 5; /config/scripts/init_bind.sh
            sleep 10; /config/scripts/port_forward.sh &
            echo "[services.d] [INFO] VPN is bound to app; checking for forwarded ports" ;;
         *) sleep 5; /config/scpripts/update_bind.sh
            echo "[services.d] [WARN] VPN is bound to app; -e PORT_FORWARD set incorrectly, defaulting to disabled" ;;
         esac ;;
      *) echo "[services.d] [CRIT] !!! -e VPN is set incorrectly; set -e VPN=yes or leave unset!!!....exiting...."
         exit 1 ;;
esac
exec \
	s6-setuidgid abc /usr/bin/transmission-daemon \
	-g /config -c /watch -f

