#!/usr/bin/with-contenv sh
# Make directories
mkdir -p \
	/downloads/complete /downloads/incomplete /watch \
        /config/scripts
# Copy tunnel bind scripts if -e VPN=yes
case "$VPN" in
     yes) [[ ! -f /config/scripts/init_bind.sh ]] && cp \
      	  /defaults/scripts/init_bind.sh /config/scripts 
          [[ ! -f /config/scripts/bind_update ]] && cp \
      	  /defaults/scripts/bind_update /config/scripts ;;
       *) break ;
esac
# Copy port update script
[[ ! -f /config/scripts/port_update ]] && cp \
        /defaults/scripts/port_update /config/scripts
# Copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json
# Permissions
chown  abc:abc \
	/config/settings.json \
        /config/scripts \
	/downloads \
	/downloads/complete \
	/downloads/incomplete \
	/watch
chmod -R 755 /config/scripts/* 

